### ISSUE TITLE
Створення базової структури проєкту та стилізації

### ISSUE THREAD

**Issue by Patter1989** [psht13/aqua-track-front#1]
Точка перелому
Налаштувати гумову верстку від 320 px, адаптивну з 375 px, tablet — 768 px, desktop — 1440 px.
Шрифти
Здійснити підключення шрифтів.
Оптимізація графіки
Оптимізувати статичні векторні та растрові зображення.
Забезпечити підтримку Retina-зображень.
Підключити svg-іконки через sprite.
Додати фавікон сторінки.

**Comment by psht13** [comment]
Додав усі моменти окрім зображень, нехай кожен вже сам завантажує те що потрібно, а оптимізацію фото я автоматизую за допомогою збірника, не треба буде оптимізовувати кожне фото окремо.
