### ISSUE TITLE
UserSettingsForm

### ISSUE THREAD

**Issue by Patter1989** [psht13/aqua-track-front#10]
Компонент UserSettingsForm
Реалізувати компонент, який надає можливість користувачеві редагувати свої дані.

Склад форми:

input (типу file) для додавання аватарки користувача.
Відображення тимчасового файлу аватарки за допомогою [URL.createObjectURL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static).
radio-button для визначення статі користувача (Woman/Man).
input для зміни:
Ім'я користувача.
Email користувача.
Поточної ваги користувача.
Кількості часу на день, який користувач проводить активно у спорті.
Денної норми споживання води користувачем.
Додаткова інформація:

Відображення формули для розрахунку рекомендованої денної норми споживання води.
Поле для відображення результату розрахунку відповідно до формули.
Кнопки:

"Save" (типу submit):
При натисканні, якщо є невалідні дані:
Відобразити помилки користувачеві.
Дані не повинні відправлятися на backend.
Якщо всі дані валідні:
Відправити запит на backend для оновлення даних користувача у форматі [FormData](https://developer.mozilla.org/ru/docs/Web/API/FormData)![Image](https://github.com/user-attachments/assets/1eb20f79-f70f-4653-b17c-f44de7eb7736)
![Image](https://github.com/user-attachments/assets/310e23ff-69da-4c88-86d6-72692c01d703)
.
У разі помилки на backend відобразити її користувачеві у вигляді notification.
Якщо запит успішний:
Закрити модальне вікно.
Оновити дані у наступних компонентах:
UserPanel
WaterDailyNorma
WaterProgressBar
WaterList
Calendar.

Адаптивність

Забезпечити адаптивність всіх компонентів для точок перелому:
Mobile: мінімальна версія з оптимізацією для вузьких екранів.
Tablet та Desktop: повноцінний вигляд з достатньою шириною для кнопок.

**Comment by BorysenkoS** [comment]
The end
