### ISSUE TITLE
HomePage (AdvantagesSection)

### ISSUE THREAD

**Issue by Patter1989** [psht13/aqua-track-front#4]
Реалізувати компонент AdvantagesSection(Секція справа) з фоновим зображенням і "поки"статичними елементами.
Інтегрувати AdvantagesSection у HomePage.![Image](https://github.com/user-attachments/assets/dc2dfdbd-e542-45ca-a20e-b13e3a1f24a0)

**Comment by BIHHI87** [comment]
Miss click, sorry.
